image:
  repository: ghcr.io/<owner>/myapp
  tag: "dev"
  pullPolicy: IfNotPresent

replicaCount: 1

env:
  APP_SECRET: "hello-test"

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: false
  className: nginx
  hosts:
    - host: myapp.local.test
      paths:
        - path: /
          pathType: Prefix
